#+LANGUAGE: es
#+OPTIONS: toc:nil title:nil
#+BIBLIOGRAPHY: fuentes.bib
#+CITE_EXPORT: biblatex
#+LATEX_HEADER: \bibliographystyle{plain}

#+LATEX_CLASS_OPTIONS: [titlepage,a4paper]
#+LATEX_HEADER: \hypersetup{colorlinks=true,linkcolor=black,urlcolor=blue,bookmarksopen=true}
#+LATEX_HEADER: \usepackage{a4wide}
#+LATEX_HEADER: \usepackage{bookmark}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{svg}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhf{}
#+LATEX_HEADER: \fancyhead[L]{TP3 - Grupo 1}
#+LATEX_HEADER: \fancyhead[R]{Teoria de Algoritmos I - FIUBA}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0.4pt}
#+LATEX_HEADER: \fancyfoot[C]{\thepage}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0.4pt}
#+LATEX_HEADER: \usemintedstyle{stata-light}
#+LATEX_HEADER: \newminted{c}{bgcolor={rgb}{0.95,0.95,0.95}}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage{fancyvrb}
#+LATEX_HEADER: \fvset{framesep=1mm,fontfamily=courier,fontsize=\scriptsize,numbers=left,framerule=.3mm,numbersep=1mm,commandchars=\\\{\}}
#+LATEX_HEADER: \usepackage[nottoc]{tocbibind}

#+NAME: setup
#+BEGIN_SRC emacs-lisp :results silent :exports none
  (setq org-latex-minted-options
    '(("bgcolor" "bg")))
#+END_SRC
#+CALL: setup[:eval never-export :results none :exports none]()

#+BEGIN_EXPORT latex
\begin{titlepage}
	\hfill\includegraphics[width=6cm]{assets/logofiuba.jpg}
    \centering
    \vfill
    \Huge \textbf{Trabajo Práctico 3 — Redes de Flujo}
    \vskip2cm
    \Large [75.29/95.06] Teoria de Algoritmos I\\
    Primer cuatrimestre de 2022\\
    \vfill
    \begin{tabular}{ | l | l | l | }
      \hline
      Alumno & Padron & Email \\ \hline
      BENITO, Agustin & 108100 & abenito@fi.uba.ar \\ \hline
      BLÁZQUEZ, Sebastián & 99673 & sblazquez@fi.uba.ar \\ \hline
      DEALBERA, Pablo Andres & 106585 & pdealbera@fi.uba.ar \\ \hline
      DUARTE, Luciano & 105604 & lduarte@fi.uba.ar \\ \hline
      PICCO, Martín & 99289 & mpicco@fi.uba.ar \\ \hline
  	\end{tabular}
    \vfill
    \begin{tabular}{ | l | l | }
      \hline
      Entrega: & Primera \\ \hline
      Fecha: & Miercoles 18 de Mayo del 2022 \\ \hline
  	\end{tabular}
    \vfill
    \vfill
\end{titlepage}
\tableofcontents
\newpage
\definecolor{bg}{rgb}{0.95,0.95,0.95}
#+END_EXPORT

* Lineamientos básicos :noexport:

 - El trabajo se realizará en grupos de cinco personas.

 - Se debe entregar el informe en formato pdf y código fuente en (.zip) en el aula virtual de la materia.

 - El lenguaje de implementación es libre. Recomendamos utilizar C, C++ o Python. Sin embargo si se desea utilizar algún otro, se debe pactar con los docentes.

 - Incluir en el informe los requisitos y procedimientos para su compilación y ejecución. La ausencia de esta información no permite probar el trabajo y deberá ser re-entregado con esta información.

 - El informe debe presentar carátula con el nombre del grupo, datos de los integrantes y y fecha de entrega. Debe incluir número de hoja en cada página. No debe superar las 20 páginas.

 - En caso de re-entrega, entregar un apartado con las correcciones mencionadas

 - En este trabajo práctico se debe investigar cada una de las partes. Se evalúa esto dentro de la nota final.

 - Debe entregar en el informe las fuentes consultadas en una sección de referencias.

* Parte 1: El viaje a Qatar

** Enunciado :noexport:
Una ONG con sede en Buenos Aires desea realizar un viaje grupal de “estudio” a
Qatar entre las fechas de 21 de noviembre de 2022 y el 18 de diciembre de 2022.
Han realizado diversas averiguaciones con compañías aéreas para conocer el costo
de pasaje y la cantidad que podrían comprar para diferentes trayectos por
ciudades del mundo. Su objetivo es determinar cuál es la máxima cantidad de
personas que podría viajar y hacerlo al menor costo posible.

Se pide:

 1. Investigar y seleccionar uno de los siguientes algoritmos que resuelven este problema conocido como flujo máximo con costo mínimo (“Min Cost Max Flow”): “Cycle Cancelling Algorithm” o “Successive shortest path algorithm”.

 2. Explicar cómo funciona el algoritmo seleccionado. Incluir: pseudocódigo, análisis de complejidad espacial, temporal y optimalidad.

 3. Dar un ejemplo paso a paso de su funcionamiento.

 4. Programar el algoritmo.

 5. Responder justificando: ¿La complejidad de su algoritmo es igual a la presentada en forma teórica?

*** Formato de los archivos:

El programa debe recibir por parámetro el path del archivo donde se encuentra el
grafo. El formato del archivo es de texto. Las primeras dos líneas corresponden
al nodo fuente y sumidero respectivamente. Continúa con una línea por cada eje
del grafo con el formato: ~ORIGEN,DESTINO,COSTO UNITARIO,CAPACIDAD~.

Ejemplo:

#+begin_src csv
BS AS
QATAR
BS AS,RIO,2,8
BS AS,MADRID,3,4
MADRID,NEW YORK,2,5
…
#+end_src

El programa debe retornar en pantalla la cantidad máxima de personas que pueden
viajar y el costo mínimo que se puede gastar.
** Intro

Una cita de stackoverflow[cite:@unacita]

** Detalles de implementación

El algoritmo fue implementado en Python y probado con la versión ~3.10.4~.

Para la ejecución del algoritmo normal no hay dependencia, para exportar el
grafo a imagen, se necesita como dependencia ~graphviz~ que se puede instalar con:

#+begin_src bash
pip install graphviz
#+end_src

*** Ejecución del programa

El programa contiene un ~shebang~ para ser ejecutado en una terminal de la
siguiente forma:

#+begin_src bash :results raw
./src/parte_1.py <filename>
#+end_src

El comprimido entregado incluye un carpeta en ~assets/~ con grafos ejemplos, por
ejemplo:

#+begin_src bash :results raw
./src/parte_1.py ./assets/grafo-qatar.csv
#+end_src

#+begin_src text
La cantidad maxima de personas que pueden viajar es:  6
El costo de todos los viajes es:  14
#+end_src

**** Exportador de Grafo a Imagen

Aparte de esto, esta incluido un exportador que genera un imagen en formato
/SVG/ de los grafos y se puede generar con el siguiente comando:

#+begin_src bash
./src/export.py ./assets/grafo-qatar.csv
#+end_src

#+ATTR_HTML: :width 800
#+ATTR_LATEX: :placement [H]
#+ATTR_LATEX: :width 0.8\textwidth
#+ATTR_LATEX: :caption \caption{\label{fig1:seq01}Hospital con un entrenador cargado.}
[[file:assets/grafo-qatar.svg]]

* Parte 2: Un reality único

** Enunciado :noexport:

Para un casting para un nuevo reality show han generado un conjunto de “k”
características que desean que tengan los diferentes participantes. Por ejemplo:
“historia trágica”, “habilidades musicales”, “capacidad atlética”, “estudios
universitarios”, “amor por los animales”, etc. Cuentan con un conjunto de “n”
personas que se anotaron con deseos de participar. Para cada característica
tienen la lista de personas que la posee. La producción desea seleccionar a un
subconjunto de participantes de forma tal de que cada una de las características
se vea representada. Además para lograr mayor variabilidad quieren que no
existan dos personas con la misma característica.

Se pide:

 1. Utilizando EXACT-COVER demostrar que el problema al que denominaremos “casting” es NP-C

 2. Demuestre que EXACT-COVER es NP-C (puede ayudarse con diferentes problemas, entre ellos 3SAT, para hacerlo)

 3. Utilizando el concepto de transitividad y la definición de NP-C explique qué ocurriría si se demuestra que el problema EXACT-COVER pertenece a la clase P.

 4. Un tercer problema al que llamaremos X se puede reducir polinomialmente a EXACT-COVER, qué podemos decir acerca de su complejidad?

 5. Realice un análisis entre las clases de complejidad P, NP y NP-C y la relación entre ellos.

* Fuentes
\printbibliography[heading=none]
